# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.110.0"
xcversion(version: "~> 8.1")
default_platform :ios
platform :ios do
  before_all do
    # run pod install before_all
    # cocoapods
    # clear_derived_data
  end

  lane :lint do
    swiftlint(
      mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
      output_file: ".framgia-ci-reports/swift-lint.xml", # The path of the output file (optional)
      config_file: ".swiftlint.yml",     # The path of the configuration file (optional)
      ignore_exit_status: false    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
    )
  end

  lane :build do
    xcodebuild(
      project: "FDMS.xcodeproj",
      scheme: "FDMS",
      configuration: "Debug",
      clean: true,
      build: true,
      destination: "generic/platform=iOS",
      build_settings: {
        "CODE_SIGNING_REQUIRED" => "NO",
        "CODE_SIGN_IDENTITY" => ""
      }
    )
  end

  lane :test do
    scan(
      scheme: "FDMS",
      device: "iPhone 7",
      clean: true,
      skip_build: true,
      output_directory: ".framgia-ci-reports/"
    )
  end

  lane :beta do

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
